# Generated by Django 4.2.11 on 2024-08-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_cep_remove_pedido_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
